language: android

android:
  components:
    - build-tools-20.0.0
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

branches:
  except:
    - gh-pages

notifications:
  email: false

before_install:
 - ./check-missing-assertions.sh

script:
 - ./gradlew clean check
